FROM ubuntu:20.04
RUN apt-get update && apt-get install lsphp74-apcu lsphp74-common lsphp74-curl lsphp74-imagick lsphp74-imap lsphp74-intl lsphp74-ioncube lsphp74-json lsphp74-memcached lsphp74-mysql lsphp74-opcache lsphp74-pear lsphp74-pgsql lsphp74-pspell lsphp74-redis lsphp74-tidy -y 
